[2025-09-01T05:03:17.004+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2025-08-31T00:00:00+00:00 [queued]>
[2025-09-01T05:03:17.021+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2025-08-31T00:00:00+00:00 [queued]>
[2025-09-01T05:03:17.022+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-09-01T05:03:17.022+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-09-01T05:03:17.022+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-09-01T05:03:17.043+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): inaccurate> on 2025-08-31 00:00:00+00:00
[2025-09-01T05:03:17.050+0000] {standard_task_runner.py:55} INFO - Started process 103 to run task
[2025-09-01T05:03:17.056+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2025-08-31T00:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmpiq01blc2']
[2025-09-01T05:03:17.056+0000] {standard_task_runner.py:83} INFO - Job 177: Subtask inaccurate
[2025-09-01T05:03:17.156+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2025-08-31T00:00:00+00:00 [running]> on host caf234be515d
[2025-09-01T05:03:17.257+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2025-08-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-31T00:00:00+00:00
[2025-09-01T05:03:17.259+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-09-01T05:03:17.260+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2025-09-01T05:03:17.279+0000] {subprocess.py:86} INFO - Output:
[2025-09-01T05:03:17.281+0000] {subprocess.py:93} INFO - inaccurate
[2025-09-01T05:03:17.281+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-01T05:03:17.316+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20250831T000000, start_date=20250901T050317, end_date=20250901T050317
[2025-09-01T05:03:17.347+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-09-01T05:03:17.373+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
