[2025-08-19T16:07:18.895+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2025-08-19T16:07:04.408476+00:00 [queued]>
[2025-08-19T16:07:18.910+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2025-08-19T16:07:04.408476+00:00 [queued]>
[2025-08-19T16:07:18.911+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-08-19T16:07:18.911+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-08-19T16:07:18.911+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-08-19T16:07:18.928+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): inaccurate> on 2025-08-19 16:07:04.408476+00:00
[2025-08-19T16:07:18.933+0000] {standard_task_runner.py:55} INFO - Started process 299 to run task
[2025-08-19T16:07:18.939+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2025-08-19T16:07:04.408476+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmpuj5z4tph']
[2025-08-19T16:07:18.939+0000] {standard_task_runner.py:83} INFO - Job 35: Subtask inaccurate
[2025-08-19T16:07:19.016+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.inaccurate manual__2025-08-19T16:07:04.408476+00:00 [running]> on host d9bec5ca469d
[2025-08-19T16:07:19.091+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2025-08-19T16:07:04.408476+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-19T16:07:04.408476+00:00
[2025-08-19T16:07:19.092+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-08-19T16:07:19.093+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2025-08-19T16:07:19.105+0000] {subprocess.py:86} INFO - Output:
[2025-08-19T16:07:19.108+0000] {subprocess.py:93} INFO - inaccurate
[2025-08-19T16:07:19.109+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-19T16:07:19.142+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20250819T160704, start_date=20250819T160718, end_date=20250819T160719
[2025-08-19T16:07:19.189+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-08-19T16:07:19.210+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
