[2025-08-20T05:00:02.228+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2025-08-19T00:00:00+00:00 [queued]>
[2025-08-20T05:00:02.253+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2025-08-19T00:00:00+00:00 [queued]>
[2025-08-20T05:00:02.253+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-08-20T05:00:02.254+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-08-20T05:00:02.254+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-08-20T05:00:02.281+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): inaccurate> on 2025-08-19 00:00:00+00:00
[2025-08-20T05:00:02.290+0000] {standard_task_runner.py:55} INFO - Started process 103 to run task
[2025-08-20T05:00:02.298+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2025-08-19T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmpkozqxa_j']
[2025-08-20T05:00:02.298+0000] {standard_task_runner.py:83} INFO - Job 84: Subtask inaccurate
[2025-08-20T05:00:02.425+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2025-08-19T00:00:00+00:00 [running]> on host 74a21df92820
[2025-08-20T05:00:02.557+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2025-08-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-19T00:00:00+00:00
[2025-08-20T05:00:02.559+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-08-20T05:00:02.560+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2025-08-20T05:00:02.586+0000] {subprocess.py:86} INFO - Output:
[2025-08-20T05:00:02.595+0000] {subprocess.py:93} INFO - inaccurate
[2025-08-20T05:00:02.600+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-20T05:00:02.645+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20250819T000000, start_date=20250820T050002, end_date=20250820T050002
[2025-08-20T05:00:02.709+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-08-20T05:00:02.769+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
