[2025-08-20T05:48:29.599+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2025-08-20T05:48:24.435631+00:00 [queued]>
[2025-08-20T05:48:29.612+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2025-08-20T05:48:24.435631+00:00 [queued]>
[2025-08-20T05:48:29.612+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-08-20T05:48:29.612+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-08-20T05:48:29.613+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-08-20T05:48:29.635+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): inaccurate> on 2025-08-20 05:48:24.435631+00:00
[2025-08-20T05:48:29.642+0000] {standard_task_runner.py:55} INFO - Started process 2415 to run task
[2025-08-20T05:48:29.647+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2025-08-20T05:48:24.435631+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmpyg3mokbn']
[2025-08-20T05:48:29.648+0000] {standard_task_runner.py:83} INFO - Job 95: Subtask inaccurate
[2025-08-20T05:48:29.730+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.inaccurate manual__2025-08-20T05:48:24.435631+00:00 [running]> on host 74a21df92820
[2025-08-20T05:48:29.813+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2025-08-20T05:48:24.435631+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-20T05:48:24.435631+00:00
[2025-08-20T05:48:29.815+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-08-20T05:48:29.816+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2025-08-20T05:48:29.829+0000] {subprocess.py:86} INFO - Output:
[2025-08-20T05:48:29.832+0000] {subprocess.py:93} INFO - inaccurate
[2025-08-20T05:48:29.833+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-20T05:48:29.867+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20250820T054824, start_date=20250820T054829, end_date=20250820T054829
[2025-08-20T05:48:29.899+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-08-20T05:48:29.922+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
